In [1]:
import numpy as np

In [43]:
# Create a 1D array of numbers from 0 to 9
import numpy as np
array = np.arange(9)
print("array from  0 to 9")
print(array)

array from  0 to 9
[0 1 2 3 4 5 6 7 8]


In [44]:
# Create a 3x3 Numpy array of numbers from 1- 10
import numpy as np
array = np.arange(2, 11).reshape(3,3)
print(array)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [42]:
# Create a 3x3 NumPy array of all Boolean value Trues
bool_arr = np.ones ((3,3), dtype=bool)
print("3x3 numpy array")
print(bool_arr)

3x3 numpy array
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [41]:
# Extract all odd numbers from array of 1 - 10
import numpy as np
a = np.array([1,2,3,4,5,6,7,8,9,10])
a[a % 2 == 1]

array([1, 3, 5, 7, 9])

In [40]:
# Replace all odd numbers in an array of 1 - 10 with the value -1
import numpy as np
a = np.arange(1,10,1)
a[a % 2 ==1] = -1
print(a)

[-1  2 -1  4 -1  6 -1  8 -1]


In [56]:
# Convert a 1D array to a 2D array with 2 rows
import numpy as np
array = np.array([1,2,3,4,5,6,7,8,9,10])
newArray = array.reshape(2,5)
print(newArray)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [74]:
# Create two arrays a and b, stack these 2 arrays vertically use the np.dot and np.sum to calculate totals
import numpy as np
a = np.arange(11,20).reshape(3,3)
b = np.arange(20,29).reshape(3,3)
np.vstack((a,b))

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19],
       [20, 21, 22],
       [23, 24, 25],
       [26, 27, 28]])

In [75]:
c = np.dot(a,b)
print(c)

[[ 834  870  906]
 [1041 1086 1131]
 [1248 1302 1356]]


In [76]:
sum = np.sum(c)
print(sum)

9774


In [80]:
# In 2 arrays a (1,2,3,4,5) and b (4,5,6,7,8,9) remove all repeating items present in array b
import numpy as np
a = np.array([1,2,3,4,5])
b = np.array([4,5,6,7,8,9])
new_array = np.unique(np.concatenate((a,b),0))
print(new_array)

[1 2 3 4 5 6 7 8 9]


In [102]:
# Get all items between 5 and 10 from a and b and sum them together
import numpy as np
array = np.arange(5,10)
print(array)
np.sum((array))

[5 6 7 8 9]


35

In [95]:
a = np.array([1,2,3])
np.r_[np.repeat(a, 3), np.tile(a, 3)]

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])